server:
  port: 5003
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:5002/eureka,http://peer3:5003/eureka
spring:
  application:
    name: spring-cloud-peer1
